# Generated by Django 3.1 on 2020-08-04 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumptionGoal', models.IntegerField(default=64)),
                ('currAmountConsumed', models.IntegerField(default=0)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_one', models.TextField(blank=True, null=True)),
                ('goal_one_completed', models.BooleanField(default=False)),
                ('goal_two', models.TextField(blank=True, null=True)),
                ('goal_two_completed', models.BooleanField(default=False)),
                ('goal_three', models.TextField(blank=True, null=True)),
                ('goal_three_completed', models.BooleanField(default=False)),
                ('goal_four', models.TextField(blank=True, null=True)),
                ('goal_four_completed', models.BooleanField(default=False)),
                ('goal_five', models.TextField(blank=True, null=True)),
                ('goal_five_completed', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=140)),
                ('anon', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
